const fs = require("fs");

const ipsum = new GenerateText();

function GenerateText() {

    this.quotes = [
        "New SpaceX Starlink cover shows transfer orbit from Earth to Mars.",
        "Congrats Tesla Team on over 200,000 car built & delivered in Q2, despite many challenges!!",
        "Super Heavy on road & 7th Tower segment added.",
        "Super Heavy moves tomorrow.",
        "Baby Doge, doo, doo, doo, doo, doo.",
        "Baby Doge.",
        "Release the Doge!",
        "Stop gendering memes.",
        "I mean mimes.",
        "Rapidly Reusable Rockets.",
        "R R R",
        "Thanks for all the happy birthday wishes!",
        "All 72 orbital planes activate in August.",
        "Plus many other improvements.",
        "Enabling global coverage",
        "Except for polar regions, which will take another 6 months.",
        "Starlink simultaneously active users just exceeded the strategically important threshold of 69,420 last night!",
        "My Shiba Inu will be named Floki.",
        "Timing is everything.",
        "“That’s not funny!” – Bitcoin maxis.",
        "How many Bitcoin maxis does it take to screw in a lightbulb?",
        "Shout out to the awesome Tesla global team.",
        "Thanks for working so hard to make Tesla successful!",
        "Looking at holding Tesla AI Day in about a month or so.",
        "Will go over progress with Tesla AI software & hardware, both training & inference.",
        "Purpose is recruiting.",
        "Happy Father’s Day!",
        "Real pic of 2 ships next to Starbase Tiki Bar on right.",
        "Let’s just skip original video games & movies & go straight to the sequel.",
        "From the top of Starbase high bay.",
        "Stacking Super Heavy Aft Section.",
        "K is Kindred.",
        "Could turn out to be one big Philip K Dick joke in the end.",
        "Pluto takes 248 years to orbit the sun, but Uranus only takes 84.",
        "!!",
        "This is true.",
        "Our Soul Dichotomy.",
        "Esoteric meme of the day:",
        "Plaid release event.",
        "Most amount of fun on 4 wheels!",
        "Pure joy on tap whenever u want.",
        "Order Tesla Model S Plaid at:",
        "0 to 60mph in under 2 secs.",
        "Quickest production car ever made of any kind.",
        "Has to be felt to be believed.",
        "Plaid+ is canceled.",
        "No need, as Plaid is just so good.",
        "Model S goes to Plaid speed this week.",
        "I guess we read the instructions haha.",
        "Goods & services are the real economy, any form of money is simply the accounting thereof.",
        "Cum rocket to the moon.",
        "Canada. USA. Mexico.",
        "Ocean spaceport Deimos is under construction for launch next year.",
        "Model S Plaid delivery pushed to June 10.",
        "Needs one more week of tweak.",
        "This car feels like a spaceship.",
        "Words cannot describe the limbic resonance.",
        "Deep thots.",
        "If only they had spaceships, they’d still be around.",
        "If only they had spaceships.",
        "Someone suggested changing Dogecoin fees based on phases of the moon, which is pretty awesome haha.",
        "Someone suggested changing Dogecoin fees based on phases of the moon.",
        "If you’d like to help develop Doge, please submit ideas on GitHub.",
        "Spoke with North American Bitcoin miners. They committed to publish current & planned renewable usage & to ask miners WW to do so. Potentially promising.",
        "Potentially promising.",
        "Spoke with North American Bitcoin miners.",
        "They committed to publish current & planned renewable usage & to ask miners WW to do so.",
        "Any sufficiently advanced magic is indistinguishable from technology",
        "How much is that Doge in the window?",
        "Credit to our Master of Coin.",
        "Tesla Model S Plaid delivery event, June 3 at our California factory.",
        "Fastest production car ever.",
        "0 to 60mph in under 2 secs.",
        "Tesla has diamond hands.",
        "Aiming for extreme precision with next gen Model Y – microns, not millimeters.",
        "Microns, not millimeters.",
        "Aiming for extreme precision with next gen Model Y.",
        "Giga Berlin suppliers please accelerate!",
        "As always.",
        "Working with Doge devs to improve system transaction efficiency. Potentially promising.",
        "Working with Doge devs to improve system transaction efficiency.",
        "To be clear, I strongly believe in crypto, but it can’t drive a massive increase in fossil fuel use, especially coal.",
        "It is high time there was a carbon tax!",
        "Energy usage trend over past few months is insane.",
        "Tesla & Bitcoin.",
        "Do you want Tesla to accept Doge?",
        "SNL Monologue.",
        "Wario was my fav haha.",
        "First time a Falcon rocket booster will reach double digits in flights.",
        "Cybertruck prototype in New York this weekend.",
        "Cryptocurrency is promising, but please invest with caution!",
        "Cryptocurrency is promising.",
        "Please invest with caution!",
        "Make humanity a multiplanet species!",
        "Public support for life on Mars is critical to making it happen.",
        "Starship landing nominal!",
        "About to launch.",
        "I love Art Deco.",
        "Baby Shark & Shark Tank merge to form Baby Shark Tank.",
        "Irony Man – defeats villains using the power of irony.",
        "Throwing out some skit ideas for SNL. What should I do?",
        "Throwing out some skit ideas for SNL.",
        "What should I do?",
        "Woke James Bond.",
        "SNL May 8.",
        "A major part of real-world AI has to be solved to make unsupervised, generalized full self-driving work, as the entire road system is designed for biological neural nets with optical imagers.",
        "The Dogefather. SNL May 8.",
        "The Dogefather.",
        "SNL May 8.",
        "Starship SN15 static fire completed, preparing for flight later this week.",
        "Starship SN15 static fire completed.",
        "Preparing for flight later this week.",
        "Let’s find out just how live Saturday Night Live really is.",
        "Am hosting SNL on May 8.",
        "define … beauty.",
        "What does the future hodl?",
        "2 mins to launch.",
        "Astronauts preparing to launch.",
        "Happy Earth Day.",
        "Tesla Solar + Powerwall battery enables consumers to be their own utility.",
        "Powerwall 2 peak & steady power capability is better than advertised.",
        "Now that we have lots of operational data, Tesla can unlock higher capabilities for free via software update next month.",
        "Depending on production date, power increase power may be >50% at 30C ambient temp.",
        "Solar power will feed exclusively to Powerwall. Powerwall will interface only between utility meter & house main breaker panel, enabling super simple install & seamless whole house backup during utility dropouts.",
        "Solar power will feed exclusively to Powerwall.",
        "Starting next week, Tesla Solar Panels & Solar Roof will only be sold as an integrated product with Tesla Powerwall battery",
        "Tesla with Autopilot engaged now approaching 10 times lower chance of accident than average vehicle.",
        "Dragon spacecraft & Falcon 9 rocket.",
        "If we make life multiplanetary, there may come a day when some plants & animals die out on Earth, but are still alive on Mars.",
        "Everything to the moon!",
        "Austin Rocks!!",
        "Make life multiplanetary!",
        "Doge Barking at the Moon.",
        "Le Petit Prince.",
        "Tesla AI/Autopilot engineering is awesome! Making excellent progress solving real-world AI.",
        "Tesla AI/Autopilot engineering is awesome!",
        "Making excellent progress solving real-world AI.",
        "Love this beautiful shot.",
        "The art In Cyberpunk is incredible.",
        "Blimps rock.",
        "Just needs some legs.",
        "The Starship launch tower that catches the giant rocket booster is basically Mechazilla.",
        "But wait how is the core of the earth lit by the sun? Stop asking questions!!",
        "Kong vs Godzilla has record for most meth ever consumed in a writer’s room.",
        "… going to moon very soon.",
        "Where is Shrek 5!?",
        "It’s all about the cufflinks.",
        "Thanks to all that helped SpaceX!",
        "Just read it. Book is accurate.",
        "Soon our monkey will be on twitch & discord haha.",
        "A monkey is literally playing a video game telepathically using a brain chip!!",
        "The device is implanted flush with skull & charges wirelessly, so you look & feel totally normal.",
        "Later versions will be able to shunt signals from Neuralinks in brain to Neuralinks in body motor/sensory neuron clusters, thus enabling, for example, paraplegics to walk again.",
        "First Neuralink product will enable someone with paralysis to use a smartphone with their mind faster than someone using thumbs.",
        "Monkey plays Pong with his mind.",
        "Thanks Tesla suppliers for providing us with critical parts!",
        "To be clear, I do support vaccines in general & covid vaccines specifically. The science is unequivocal.",
        "In very rare cases, there is an allergic reaction, but this is easily addressed with an EpiPen.",
        "“Tanks for the memery!” – Panzer of the Lake.",
        "The Earth is not flat, it’s a hollow globe & Donkey King lives there!",
        "Godzilla vs Kong is so amaze much wow!",
        "Most insane movie I’ve ever seen!",
        "Love letter to conspiracy theorists!",
        "And yet heartwarming in the end.",
        "Urgent need to build more housing in greater Austin area!",
        "Austin++.",
        "No it doesn’t hurt at all.",
        "Me in my sick new car.",
        "SpaceX is going to put a literal Dogecoin on the literal moon.",
        "Nicheman — his superpower is appealing to small audiences.",
        "Over 10,000 people are needed for Giga Texas just through 2022!",
        "Starbase will grow by several thousand people over the next year or two.",
        "Probably most “in space” you could possibly feel by being in a glass dome.",
        "Am donating $20M to Cameron County schools & $10M to City of Brownsville for downtown revitalization. Details to follow next week.",
        "Details to follow next week.",
        "Please consider moving to Starbase or greater Brownsville/South Padre area in Texas & encourage friends to do so!",
        "SpaceX’s hiring needs for engineers, technicians, builders & essential support personnel of all kinds are growing rapidly.",
        "FAA inspector unable to reach Starbase in time for launch today. Postponed to no earlier than tomorrow.",
        "Postponed to no earlier than tomorrow.",
        "FAA inspector unable to reach Starbase in time for launch today.",
        "Possible Starship flight tomorrow afternoon.",
        "Wholesome memes.",
        "Check out our new crane.",
        "If there’s ever a scandal about me, *please* call it Elongate.",
        "Don’t defy DeFi.",
        "Mars rover looking back.",
        "Pay by Bitcoin capability available outside US later this year.",
        "Tesla is using only internal & open source software & operates Bitcoin nodes directly.",
        "Bitcoin paid to Tesla will be retained as Bitcoin, not converted to fiat currency.",
        "You can now buy a Tesla with Bitcoin.",
        "Music in zero gravity.",
        "First Super Heavy Booster.",
        "The simulation really struggled to make this look real haha.",
        "I’m selling this song about NFTs as an NFT.",
        "Actually, doesn’t feel quite right selling this. Will pass.",
        "Will pass.",
        "Actually, doesn’t feel quite right selling this.",
        "I love music. It makes my heart sing.",
        "This is good.",
        "Play your favorite song in a Tesla & turn the volume to 11.",
        "You will see. You will feel.",
        "You will see.",
        "You will feel.",
        "A puckish rogue.",
        "Falcon flies for the 9th time tonight.",
        "I’m getting a Shiba Inu.",
        "Homo sapiens techno: Loves raves & technology.",
        "Why are you so dogematic, they ask.",
        "The ancient Romans sacrificed a Dogecoin at the beginning of the Doge Days to appease the rage of Sirius, believing that the star was the cause of the hot, sultry weather.",
        "Doge day afternoon.",
        "Woketopia. Battle for the Moral High Ground in this new game!",
        "Both do mining & use blocks & chains.",
        "BTC (Bitcoin) is an anagram of TBC(The Boring Company). What a coincidence!",
        "What a coincidence!",
        "Next significant release will be in April. Going with pure vision — not even using radar. This is the way to real-world AI.",
        "FSD Beta has now been expanded to ~2000 owners & we’ve also revoked beta where drivers did not pay sufficient attention to the road. No accidents to date.",
        "No accidents to date.",
        "Carnot efficiency of the Universe?",
        "Great band, too bad they broke up.",
        "Due to high levels of demand for FSD Beta, adding “Download Beta” button to Service section of car display in ~10 days.",
        "Availability varies by region due to regulatory approval delays and/or Tesla internal development & testing.",
        "All software is first tested internally by Tesla simulation & QA drive teams.",
        "Note: word “Beta” is used to reduce complacency in usage & set expectations appropriately.",
        "Doge spelled backwards is Egod.",
        "Cybervikings of Mars.",
        "Starship SN10 landed in one piece!",
        "Launch abort on slightly conservative high thrust limit. Increasing thrust limit & recycling propellant for another flight attempt today.",
        "Increasing thrust limit & recycling propellant for another flight attempt today.",
        "Launch abort on slightly conservative high thrust limit.",
        "5 mins to Starship test flight attempt.",
        "March 3rd.",
        "Starship launch tomorrow. Window opens at 9am.",
        "Starship launch tomorrow.",
        "Window opens at 9am.",
        "From thence to Mars, And hence the Stars.",
        "Creating the city of Starbase, Texas",
        "Horses are even self-driving!",
        "Scammers & crypto should get a room.",
        "Green eggs & SPAC.",
        "Doge meme shield (legendary item).",
        "New drug coming out called Regretamine. Pop one & all regrets are gone.",
        "Always wondered where exactly your gaming character keeps all the stuff.",
        "Do androids dream of electric cars?",
        "Not a meta4, I mean actual books.",
        "I admit to judging books by their cover.",
        "Starship to the moon.",
        "Out on launch pad, engine swap underway.",
        "You might see much higher download speeds on Starlink at times. Testing system upgrades.",
        "Testing system upgrades.",
        "On the actual moon.",
        "Literally.",
        "Excession.",
        "Of spaceflight.",
        "Hypernominalization.",
        "Dojo 4 Doge.",
        "Cryptocurrency explained.",
        "Or did they say pegged to the dollar? Something like that …",
        "Heard a rumor some crypto coin was pegging the dollar.",
        "I just want to start a flame in your heart.",
        "Just for a day.",
        "I will literally pay actual $ if they just void their accounts.",
        "If major Dogecoin holders sell most of their coins, it will get my full support. Too much concentration is the only real issue imo.",
        "было бы большой честью поговорить с вами",
        "Kremlin, would you like join me for a conversation on Clubhouse?",
        "Lil meme juice for the weekend.",
        "Happy New Year of the Ox!",
        "Frodo was the underdoge, All thought he would fail, Himself most of all.",
        "The most entertaining outcome is the most likely.",
        "Bought some Dogecoin for lil X, so he can be a toddler hodler.",
        "This is true power haha.",
        "XPrize team will manage the $100M carbon capture prize.",
        "Back to work I go …",
        "Ð is for Ðogecoin! Instructional video.",
        "The people have spoken …",
        "Who let the Doge out?",
        "Hodl the rainforests!!",
        "So … it’s finally come to this …",
        "Lessons learned.",
        "Of Earth and Mars.",
        "Time to tell the story of Tesla & SpaceX.",
        "The Second Last Kingdom.",
        "The great thing about restaurants is that you get to hang out with strangers!",
        "The future currency of Earth.",
        "Much wow!",
        "I am become meme, Destroyer of shorts",
        "Sandstorm is a masterpiece.",
        "Next time, we try pull *up* method.",
        "Low-key Loki.",
        "No highs, no lows, only Doge.",
        "No need to be a gigachad to own.",
        "Dogecoin is the people’s crypto.",
        "ur welcome.",
        "Doge.",
        "Off Twitter for a while.",
        "It will be filled with graffiti art.",
        "Giga Berlin progress.",
        "Feels weird helping make (hopefully good version of) Cyberpunk come true.",
        "Warm, sunny day & snowy mountains.",
        "What a beautiful day in LA.",
        "In retrospect, it was inevitable.",
        "With Cyberpunk, even the hotfixes literally have hotfixes, but … great game.",
        "First production car ever to achieve 0 to 60 mph in less than 2 seconds.",
        "It can play Cyberpunk.",
        "Even Discord has gone corpo …",
        "Plaid Model S ships next month.",
        "Gamestonk!!",
        "I kinda love Etsy.",
        "Monty Python is amazing.",
        "Legalize comedy.",
        "Use Signal.",
        "The most entertaining outcome is the most likely.",
        "As seen from an external observer, not the participants.",
        "This is called the domino effect.",
        "Because of the large footprint, it may seem flat, but actually ranges up to 5 stories tall.",
        "Ignore the heading."
    ];
}

GenerateText.prototype.getRandomQuote = function() {
    return this.quotes[Math.floor(Math.random() * this.quotes.length)];
}

GenerateText.prototype.generateParagraph = function() {
    let paragraph = "";
    let firstSentence = true;

    while (paragraph.length < 800) {
        if(firstSentence) {
            paragraph = paragraph.concat(this.getRandomQuote());
            firstSentence = false;
        } else {
            paragraph = paragraph.concat(" " + this.getRandomQuote());
        }
    }
    return paragraph;
}

GenerateText.prototype.generateParagraphs = function(numberOfParagraphs) {
    let paragraphs = [];

    while (paragraphs.length < numberOfParagraphs) {
        paragraphs.push(this.generateParagraph());
    }

    let paragraphHTML = "";
    paragraphs.forEach(function (paragraph) {
      paragraphHTML += "<p>" + paragraph + "</p>";
    });
    return paragraphHTML;
  }

  module.exports = ipsum;